### ISSUE TITLE
Ten stars render on profile page where five are expected

### ISSUE THREAD

**Issue by 1andee** [tahuana/LHL_Project7_Final#26]
In some situations, RatyRate gem duplicates the star assets twice in-line on user profile page before reverting back to the correct number (five).

This behaviour has been observed when:
- Reloading own profile via top-right navbar link
- Returning to show user from edit own profile form

**Comment by Chasteau** [comment]
I am still searching for this bug, I have yet to see it on my end.

**Comment by 1andee** [comment]
It appears that I can no longer duplicate this bug. Marking as resolved.

**Comment by 1andee** [comment]
No longer able to duplicate. Marking as fixed. Thx.

**Comment by 1andee** [comment]
Resolved in commit 94d4e954e29891777d816288db36bc052dcfac2f
